#FROM arm32v6/alpine
FROM alpine

LABEL maintainer="drtestonek"

RUN apk add build-base
RUN apk add make
RUN apk add cmake
RUN apk add perl

COPY gromacs-2020.1.tar.gz .
RUN tar xfz gromacs-2020.1.tar.gz
RUN mkdir  gromacs-2020.1/build 
RUN cd gromacs-2020.1/build ; cmake .. -DGMX_BUILD_OWN_FFTW=ON -DREGRESSIONTEST_DOWNLOAD=ON
RUN cd gromacs-2020.1/build ; make
RUN cd gromacs-2020.1/build ; make check
RUN cd gromacs-2020.1/build ; make install
CMD ["sh", source /usr/local/gromacs/bin/GMXRC]


